language: python

env:
  - DOCKER_COMPOSE_VERSION=3.3
before-install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install coveralls


script:
  - black --check .
  - flake8
  - python manage.py collectstatic
  - coverage run --source='.' manage.py test
  - docker compose run web python manage.py check
  - docker compose run web python manage.py migrate
  - docker compose up
  - docker compose down


after_success:
  - coveralls